InnovationAndStartupSocialNetworkPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls'), name='account_app'),
    path('userpage/', include('userpage.urls', namespace='userpage')),
    path('course/', include('course.urls'), name='course'),
    path('message/', include('messanger.urls', namespace='message')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

course/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('', views.courseHome, name='coursehome'),
    path('post', views.post, name='post'),
    path("delete/<int:courseId>", views.delCourse, name='delcourse'),
    path('enroll', views.enrollCourse, name='enroll'),

    
]

messanger/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'message'

urlpatterns = [
    path("<str:username>", views.message, name="semessage"),
]

templates/message/semessage.html
{% extends 'base.html' %}

{% block body %}
<h1>Hello {{user}}</h1>

<form method="Post" action="{% url 'message:semessage' request.user %}" enctype="multipart/form-data">
{% csrf_token %}
	<input class="form-control mr-sm-2" type="search" placeholder="Receiver Username" aria-label="Search" name="receiver">
	<textarea type="text" class="form-control" id="message_text" name="message" placeholder="Write your message here" rows="5"></textarea>
	<label for="image">Image : </label>
    <input type="file" name="image" id="image"><br>
	<button type="submit" class="btn btn-warning" id="message">Send</button>
</form>
<hr style="border-top: 2px solid #000000;">

<h1>Messages for you</h1>
{% for rec in recmsg %}
<p><pre>{{rec.msg}} --Sended by {{rec.sender.username}} at {{rec.dat.time}} {{rec.dat.date}}</pre></p>
{% if rec.pict %}
<img src="{{rec.pict.url}}" alt="..." width="460" height="360">
{% endif %}
<hr style="border-top: 2px solid #000000;">
{% endfor %}

<h1>Messages you send</h1>
{% for sen in senmsg %}
<p><pre>{{sen.msg}} --Sended to {{sen.reciver.username}} at {{sen.dat.time}} {{sen.dat.date}}</pre></p>
{% if sen.pict %}
<img src="{{sen.pict.url}}" alt="..." width="460" height="360">
{% endif %}
<hr style="border-top: 2px solid #000000;">

{% endfor %}

{% endblock body %}